find_path(SDL2_TTF_INCLUDE_DIR SDL_ttf.h
  HINTS
    ${SDL2_PATH}
    ENV SDL2_PATH
  PATH_SUFFIXES SDL2 include/SDL2 include
)

find_library(SDL2_TTF_LIBRARY
  NAMES SDL2_ttf
  HINTS
    ${SDL2_PATH}
    ENV SDL2_PATH
  PATH_SUFFIXES lib
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SDL2_ttf DEFAULT_MSG SDL2_TTF_LIBRARY SDL2_TTF_INCLUDE_DIR)

if(SDL2_TTF_FOUND)
  set(SDL2_TTF_LIBRARIES ${SDL2_TTF_LIBRARY})
  set(SDL2_TTF_INCLUDE_DIRS ${SDL2_TTF_INCLUDE_DIR})
else()
  set(SDL2_TTF_LIBRARIES)
  set(SDL2_TTF_INCLUDE_DIRS)
endif()

mark_as_advanced(SDL2_TTF_INCLUDE_DIR SDL2_TTF_LIBRARY)

